steps:
- name: 'python'
  entrypoint: 'python'
  args: ['-m', '/usr/bin/dev_appserver.py --runtime_python_path=/usr/bin/python3 --application=ultra-thought-397322 app.yaml --port=9000']
- name: 'python'
  entrypoint: 'python'
  args: ['-m', 'pytest']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'  
  entrypoint: 'bash'
  args: ['-c', 'gcloud config set app/cloud_build_timeout 1600 && gcloud app deploy']
timeout: '1600s'
options:
  logging: CLOUD_LOGGING_ONLY
